### ISSUE TITLE
get_hotspot crashed after 4 hours

### ISSUE THREAD

**Issue by gradoj** [tedder/helium_hotspot_exporter#1]
It ran for hours and then crashed...i removed the hotspot address from below.
```
helium_hotspot_exporter.py:req_get_json:86:DEBUG	fetching url: https://api.helium.io/v1/hotspots/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
helium_hotspot_exporter.py:req_get_json:88:DEBUG	fetch returned: <Response [503]>
Traceback (most recent call last):
  File "/opt/app/helium_hotspot_exporter.py", line 298, in <module>
    stats()
  File "<decorator-gen-1>", line 2, in stats
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/context_managers.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "/opt/app/helium_hotspot_exporter.py", line 286, in stats
    stats_for_hotspot(addr, hname)
  File "/opt/app/helium_hotspot_exporter.py", line 173, in stats_for_hotspot
    d = get_hotspot(addr)
  File "/opt/app/helium_hotspot_exporter.py", line 122, in get_hotspot
    return ret['data']
KeyError: 'data'
```

**Comment by tedder** [comment]
cool, figured I'd start seeing non-200s at some point. I'll fix.
